language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - "pip install -q nose==1.1.2 WebTest==1.4.0 --use-mirrors"
  - "pip install -q -e . --use-mirrors"
# command to run tests, e.g. python setup.py test
script:
  - "nosetests"
